version: '3.5'

services:
  app:
    container_name: pharmacy_web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
      - default
    ports:
      - '3013:3013'
    environment:
      - API_PORT=3013
      - API_VERSION=0.1.0-beta.02
      - MONGO_URL=mongodb://app-db:27017/app
      - MONGO_USER=admin
      - MONGO_PWD=admin
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:www.farmaciamila.com.br"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=3013"
      # - "traefik.basic.frontend.rule=Host:www.farmaciamila.com.br"
      # - "traefik.basic.port=3013"
      # - "traefik.basic.protocol=http"
    
networks:
  web:
    external: true